parameters: {}
environment:
  LOG_DESTINATIONS: ${LOG_DESTINATIONS}
packages:
  - name: sample
    shared: false
    environment: {}
    parameters: {}
    annotations: {}
    functions:
      - name: hello
        runtime: nodejs:18
        main: ""
        web: true
        binary: false
        webSecure: false
        parameters: {}
        environment: {}
        annotations: {}
        limits: { timeout: 120000 }
