parameters: {}
packages:
  - name: sample
    environment:
      LOG_DESTINATIONS: ${LOG_DESTINATIONS}
      FOO: ${FOO}
    functions:
      - name: hello
        runtime: "nodejs:default"
        limits: { timeout: 120000 }
