parameters: {}
environment:
  LOG_DESTINATIONS: ${LOG_DESTINATIONS}
packages:
  - name: sample
    functions:
      - name: hello
        runtime: "nodejs:default"
        limits: { timeout: 120000 }
